In [1]:
import stats

In [2]:
stats.mean([12,23,23,2,3,5])


11.333333333333334

In [3]:
from stats import mode,standard_deviation
mode([12,23,21,43,5,5,5])

5

In [5]:
import numpy as np


In [6]:
a=np.array([1,2,3,4,5,6])

In [8]:
type(a)

numpy.ndarray

In [10]:
a.mean()

3.5

In [11]:
a.ndim

1

In [12]:
a.dtype

dtype('int32')

In [16]:
b=np.array([1.1,2,3,4,5,6],dtype=str)
b.dtype

dtype('<U3')

In [19]:
b=b.astype(float)
b

array([1.1, 2. , 3. , 4. , 5. , 6. ])

In [29]:
b[1]

2.0

In [21]:
x=np.arange(1,21)

In [26]:
m=x.reshape(5,4)

In [33]:
m[0:2,0]

array([1, 5])

In [34]:
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [35]:
m[2:,-2:]

array([[11, 12],
       [15, 16],
       [19, 20]])

In [38]:
m[0:3,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [39]:
np.save("m_matrix",m)

In [40]:
n=np.load("m_matrix.npy")

In [41]:
n

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [42]:
np.savetxt("m_matrix.txt",m)

In [43]:
np.loadtxt("m_matrix.txt")

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.],
       [17., 18., 19., 20.]])

In [46]:
a>5

array([False, False, False, False, False,  True])

In [47]:
m[m>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [49]:
m*10

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160],
       [170, 180, 190, 200]])

In [50]:
m*n

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144],
       [169, 196, 225, 256],
       [289, 324, 361, 400]])

In [54]:
n=x.reshape(4,5)

In [55]:
np.dot(m,n)

array([[110, 120, 130, 140, 150],
       [246, 272, 298, 324, 350],
       [382, 424, 466, 508, 550],
       [518, 576, 634, 692, 750],
       [654, 728, 802, 876, 950]])

In [57]:
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [56]:
m.T

array([[ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19],
       [ 4,  8, 12, 16, 20]])

In [59]:
sq_m=np.array([1,23,34,5]).reshape(2,2)

In [60]:
np.linalg.inv(sq_m)

array([[-0.00643501,  0.02960103],
       [ 0.04375804, -0.001287  ]])

In [44]:
import os

In [ ]:
#os.chdir("C/sdsad")

In [63]:
def factorial(x):
    if x==1 or x==0:
        return 1
    else:
        return x*factorial(x-1)
def combinition(n,x):
    return factorial(n)/(factorial(x)*factorial(n-x))

In [64]:
combinition(6,0)*(0.3**0)*(0.7**6)

0.11764899999999996

In [65]:
def binomial(x,n,p):
    return combinition(n,x)*(p**x)*((1-p)**(n-x))

In [66]:
binomial(6,6,0.3)

0.0007289999999999998

In [70]:
#atleast 3 bullets
binomial(6,6,0.3)+binomial(5,6,0.3)+binomial(4,6,0.3)+binomial(3,6,0.3)

0.2556899999999999

In [71]:
n=10
x=0
p=0.1
binomial(x,n,p)

0.3486784401000001

In [72]:
n=5
p=0.2
x=0

1-binomial(x,n,p)

0.6723199999999999

In [73]:
n=8
p=0.13
x=0

1-binomial(x,n,p)

0.6717883284562879

In [112]:
s=10000000
x=np.random.binomial(5, 0.2, size=s)
len(x[x>0])/s

0.6722721

In [113]:
s=10000000
x=np.random.binomial(10, 0.1, size=s)
len(x[x==0])/s

0.3488108

In [114]:
def cumulative_binomial(x,n,p):
    total=0
    for i in range(0,x+1):
        total=total+binomial(i,n,p)
    return total

In [115]:
1-cumulative_binomial(15,18,0.9)

0.7337959947853292

In [116]:
binomial(3,500,0.001)

0.012594945443747703

In [117]:
1- cumulative_binomial(2,500,0.001)

0.014330797584369392

In [118]:
def poisson(x,lam):
    e=2.71828
    return e**(-lam)*lam**(x)/factorial(x)

In [119]:
lam=500*0.001
poisson(3,lam)

0.012636059660519087

In [120]:
n=6
p=0.3
print(n*p)

1.7999999999999998


In [122]:
s=10000000
x=np.random.binomial(6, 0.3, size=s)
np.mean(x)

1.7999545

In [136]:
s=10000000
lam=20
p=np.random.poisson(lam=lam, size=s)
len(p[p>25])/s

0.1120816

In [127]:
s=10000000
lam=10
p=np.random.poisson(lam=lam, size=s)
len(p[p>=15])/s

0.0836119

In [128]:
def cumulative_poisson(x,lam):
    total=0
    for i in range(0,x+1):
        total=total+poisson(i,lam)
    return total

In [135]:
1-cumulative_poisson(24,20)

0.15676127776617554

In [ ]:
P[0]+p[1]+....P[25]+p[26].... + p[inf]=1
P[25]+p[26].... + p[inf]=1-P[0]+p[1]+....P[24]

In [144]:
s=10000000
lam=50000
p=np.random.poisson(lam=lam, size=s)
len(p[p>=52000])/s

0.0

In [147]:
import math as m
def normal_pdf(x,mu=60,sigma=16):
    A=(2*m.pi*(sigma**2))**0.5
    B=-((x-mu)**2)/(2*sigma**2)
    return (m.e**B)/A

panda.priyansu@gmail.com

In [155]:
from scipy.integrate import quad
#print(quad.__doc__)
prob,error=quad(normal_pdf,a=0,b=55)

In [162]:
#more than 70
prob,error=quad(normal_pdf,a=0,b=70)
1-prob

0.26607394633390125

In [165]:
prob,error=quad(normal_pdf,a=70,b=(60+4*16))
prob

0.2659538578068675

In [166]:
prob,error=quad(normal_pdf,a=(60-16),b=(60+16))
prob

0.682689492137086

In [167]:
prob,error=quad(normal_pdf,a=(60-2*16),b=(60+2*16))
prob

0.9544997361036417

In [168]:
prob,error=quad(normal_pdf,a=(60-3*16),b=(60+3*16))
prob

0.9973002039367399

In [169]:
prob,error=quad(normal_pdf,a=(60-4*16),b=(60+4*16))
prob

0.999936657516334

In [171]:
prob,error=quad(normal_pdf,a=45,b=65)
prob*1000

448.41900658961475

In [157]:
print(prob,error)

0.37724186424464223 4.2851671065918704e-14


In [161]:
s=1000000
n=np.random.normal(loc=60,scale=16,size=s)
len(n[n<=55])/s

0.377783

In [163]:
s=1000000
n=np.random.normal(loc=60,scale=16,size=s)
len(n[n>=70])/s

0.265994